src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/adminpanelsubdomain/businesslayer/AdminPanelService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/businesslayer/AuthenticationService.java, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/businesslayer/AuthenticationServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/feeedbacksubdomain/businesslayer/FeedbackService.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/businesslayer/FitnessPackageService.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/businesslayer/FitnessPackageServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/FitnessPackageController.java, src/main/java/com/fitwsarah/fitwsarah/personaltrainerpanelsubdomain/businesslayer/TrainerPanelService.java, src/main/java/com/fitwsarah/fitwsarah/profilesubdomain/businesslayer/ProfileService.java
https://champlainsaintlambert.atlassian.net/browse/FWS-14
This ticket is about a need to implement the basic functions inside the business layer to facilitate the transition of making the backend part of our stories inside of the business layer easier to do
-The addition of the basic crud and other functions/methods related to our future stories
-Proper Naming Convention
=> Fws 14/business logic layer setup

src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountController.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountResponseModel.java, src/main/java/com/fitwsarah/fitwsarah/adminpanelsubdomain/presentationlayer/AdminPanelController.java, src/main/java/com/fitwsarah/fitwsarah/adminpanelsubdomain/presentationlayer/AdminPanelRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/adminpanelsubdomain/presentationlayer/AdminPanelResponseModel.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentResponseModel.java, src/main/java/com/fitwsarah/fitwsarah/feeedbacksubdomain/presentationlayer/FeedbackController.java, src/main/java/com/fitwsarah/fitwsarah/feeedbacksubdomain/presentationlayer/FeedbackRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/feeedbacksubdomain/presentationlayer/FeedbackResponseModel.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/FitnessPackageController.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/FitnessPackageRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/PromoOfferRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/PromoOfferResponseModel.java, src/main/java/com/fitwsarah/fitwsarah/profilesubdomain/presentationlayer/ProfileController.java
https://champlainsaintlambert.atlassian.net/browse/FWS-13
This ticket is about setting the the presentation layer for the subdomains inside the backend.
- Added all needed request endpoints in the controllers
- Implemented the request/response models
- This affects the entire project
=> conf/FW- 13/Presentation_layer_setup

docker-compose.yml, fitwsarah_frontend/Dockerfile.react, fitwsarah_frontend/package-lock.json, fitwsarah_frontend/package.json, fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/components/home/FitnessServiceCard.js, fitwsarah_frontend/src/components/home/home.js, fitwsarah_frontend/src/components/layout/layout.js, fitwsarah_frontend/src/index.js, fitwsarah_frontend/src/models/FitnessService.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datamapperlayer/InvoiceResponseMapper.java, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/datalayer/AuthenticationRepository.java, src/main/java/com/fitwsarah/fitwsarah/feeedbacksubdomain/datalayer/FeedbackRepository.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/businesslayer/FitnessPackageServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/datalayer/FitnessPackageRepository.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/FitnessPackageController.java, src/main/java/com/fitwsarah/fitwsarah/personaltrainerpanelsubdomain/datalayer/TrainerPanelRepository.java, src/main/java/com/fitwsarah/fitwsarah/profilesubdomain/datalayer/ProfileRepository.java, src/main/resources/data-mysql.sql, src/main/resources/schema-mysql.sql
https://champlainsaintlambert.atlassian.net/browse/FWS-26
What is the ticket about and why are we making this change?
The ticket was to implement the get-all fitness services. This change is made to display them on the web page.
What are the various changes and what other modules do those changes affect?
Added backend implementation for get all services.
Added frontend implementation for get all services.
Created a Fitness Service Card that is being display for all services.
Added dockerfile for the react app.
Frontend UI
=> feat(FWS-26): Ability to display all fitness services and packages

build.gradle, fitwsarah_frontend/src/models/FitnessService.js, src/test/java/EndToEndTesting.java
=> End-To-End Testting

fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/README.txt, fitwsarah_frontend/src/views/HomePage/FitnessService.js, fitwsarah_frontend/src/views/home/home.html, fitwsarah_frontend/src/views/layout/layout.html
https://champlainsaintlambert.atlassian.net/browse/FWS-64
This ticket is about restructuring the frontend to be clearer and easier to work with.
- Added a README file as context/ a reminder for folders
- Added several new folders like hooks (reusable components) 
- Switched naming (models -> views)
- This affects the frontend
=> FWS-64/Restructure_The_frontend

src/test/java/EndToEndTesting.java
https://champlainsaintlambert.atlassian.net/browse/FWS-33
Context:
This ticket is about implementing testing for the front end service card
Changes
Added selenium testing for service card.
=> feat(FWS- 33) : ability to view profile account page

fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/components/navigation/loggedIn/navLoggedIn.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminAccounts.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointment.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointments.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminPanel.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAccounts.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAccounts.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerPanel.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerPanel.js, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/java/com/fitwsarah/fitwsarah/fitnesspackagesubdomain/presentationlayer/FitnessPackageController.java, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-75
This ticket is about being able to view all the appointments in the system from the personal trainer panel by the trainer in the system. The function has also been added to the admin panel as well since the admin can view all the appointments as well. The purpose of this ticket was to allow the personal trainer to manage all the appointments that are either scheduled, completed or cancelled in the system.
-Selenium Test
-backend for the get-all appointments
-Front end for the get-all appointments
- Trainer Panel view is completely working …
=> feat(FWS-75): Ability to View Trainer All Appointments

fitwsarah_frontend/src/config.json, fitwsarah_frontend/src/index.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointments.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.js, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/datalayer/Appointment.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/datalayer/Status.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentResponseModel.java, src/main/resources/data-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-19
This ticket is about being able to cancel an appointment as a personal trainer and an admin by setting the status of an appointment to cancel. This ticket is important because we want to be able to cancel an appointment without it being completely deleted so but setting the status to cancelled we keep it in the database for future use.
-Selenium Test
-backend for the updateAppointmentStatus
-Front end for the updateAppointmentStatus
-Cancel appointment button working
-Alert window before cancelling
-Changed 
**UI Change:**
Before clicking: …
=> feat(FWS-19): Ability To Cancel An Appointment

build.gradle, fitwsarah_frontend/package-lock.json, fitwsarah_frontend/package.json, fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/components/authentication/RoleBasedLink.js, fitwsarah_frontend/src/components/authentication/authUtils.js, fitwsarah_frontend/src/components/authentication/roles.js, fitwsarah_frontend/src/components/navigation/loggedIn/navLoggedIn.js, fitwsarah_frontend/src/views/HomePage/FitnessService.js, fitwsarah_frontend/src/views/HomePage/Home.js, fitwsarah_frontend/src/views/ProfilePage/Account.js, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfig.java, src/main/resources/application.properties, src/main/resources/application.yml, src/main/resources/schema-mysql.sql, src/test/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfigTest.java, src/test/java/com/fitwsarah/fitwsarah/profilesubdomain/businesslayer/ProfileServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/profilesubdomain/datalayer/ProfileRepositoryTest.java, src/test/java/com/fitwsarah/fitwsarah/profilesubdomain/presentationlayer/ProfileControllerIntegrationTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-73
What is the ticket about and why are we making this change?
This ticket was about adding roles. Roles are a great way to differentiate the different users.
What are the various changes and what other modules do those changes affect?
-Added Admin Role
-Adding Personal Trainer Role
-Added Member Role
-Member role is automatically added when the user first login and passed in the token for verification.
How to use it?
Add the  .requestMatchers("endpoint").hasRole("NameOfTheRole") in the SecurityConfig File.
This is an example of a link that uses roles you need to pass the user from auth0, the role form the ROLES files and the where it is going. You also need to import there's 2 files:
=> conf/(FWS-73) Configure User Roles

fitwsarah_frontend/package.json, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointment.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointments.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.js, package-lock.json, package.json, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/datalayer/Appointment.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfig.java, src/main/resources/data-mysql.sql, src/main/resources/schema-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-21
This ticket is about being able to update the update details in the personal trainer/admin panel so that the personal trainer can change information that isn't to their liking like the status, location, first name, last name, phone number, date and time of the appointment. The reason why this is important is because like I said before the personal trainer/admins need to be able to update the information of every appointment if they feel like it if the appointment isn't to their liking.
-Selenium Test
-backend for the …
=> feat(FWS-21): Ability To Edit Appointment Details

docker-compose.yml, fitwsarah_frontend/package-lock.json, fitwsarah_frontend/package.json, fitwsarah_frontend/src/components/clientProfile/profile.js, fitwsarah_frontend/src/components/clientProfile/setting.js, fitwsarah_frontend/src/css/style.css, fitwsarah_frontend/src/views/ProfilePage/Account.css, fitwsarah_frontend/src/views/ProfilePage/Account.js, fitwsarah_frontend/src/views/ProfilePage/AppointmentCard.js, fitwsarah_frontend/src/views/authentication/Signup.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountController.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/datalayer/AppointmentRepository.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfig.java, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/AccountRepositoryTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/AccountControllerUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-59
What is the ticket about and why are we making this change?
This ticket is about being able to update a member's profile settings in the profile sidebar panel so that a member can view their account information and update their information if needed.
What are the various changes and what other modules do those changes affect?
-Adding an update feature, which allows a member to update their personal information
-Selenium Test
-backend for the update account
-Front end for the updateAccount
UI Change:
=> feat(FWS-59): Ability to edit profile page

fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminAccounts.css, fitwsarah_frontend/src/views/AdminPanelPage/FitnessServices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerFitnessServices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerPanel.js, src/main/resources/data-mysql.sql
https://champlainsaintlambert.atlassian.net/browse/FWS-79
What is the ticket about and why are we making this change?
This ticket is about being able to view fitness services as an admin and as a personal trainer.
What are the various changes and what other modules do those changes affect?
-Adding an update feature, which allows a member to update their personal information
- implemented get all fitness services for both trainer and admin panel
-changed the other information description for fitness services in data.sql file.
UI changes:
=> feat(FWS-79):Ability to get Fitness Services as a Trainer

fitwsarah_frontend/src/components/AdminPanel/Filter.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointment.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminAppointments.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.js, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/resources/data-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-55
This ticket concerns handling an appointment request as a trainer/admin when a client books an appointment. This is important because the trainer/admin needs to be able to either accept or deny an appointment if the appointment isn't to their liking or to accept it if it is to their liking and they wish to proceed by going through with the appointment. The handle appointment request combines two endpoints the set appointment status to scheduled (accept) and the set status to cancelled (deny).
-2 types of testing
-integrated testing will be done in my next pr …
=> feat(FWS-55): Ability To Handle Appointment Request

fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminPanel.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerAppointments.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerPanel.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceIndentifier.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceRepository.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/Invoices.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datamapperlayer/InvoiceRequestMapper.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datamapperlayer/InvoiceResponseMapper.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceController.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceResponseModel.java, src/main/resources/data-mysql.sql, src/main/resources/schema-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceUniyTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceRepositoryTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-86
This ticket concerns being able to view all the invoices in the system from the admin/trainer panel. This ticket is important because as an admin/trainer I want to be able to see all the invoices in the system.
-2 types of testing
-integrated testing will be done in my next PR due to a deployment issue
-Selenium Test
-backend for the getAllInvoices
-Front end for the getAllInvoices
-Added both Admin/Trainer panel invoice box and their own invoice page
**UI Change:**
After Trainer Panel:
After clicking Invoices:
=> feat(FWS-86): Ability To View All Invoices Admin/Trainer Panel

fitwsarah_frontend/package.json, fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/LanguageConfig/i18n.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminCreateInvoice.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminCreateInvoice.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCreateInvoice.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCreateInvoice.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/AccountServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceStatus.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/Invoices.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceController.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceRequestModel.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceResponseModel.java, src/main/resources/data-mysql.sql, src/main/resources/schema-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceUniyTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-62
This ticket concerns being able to create an invoice as a trainer/admin on a client. This is important because as a trainer you want to be able to add an invoice to a client that hasn't paid for the fitness appointment that they had with the trainer. This is a way of reminding a client that they haven't paid yet.
-2 types of testing
-integrated testing will be done in my next PR due to a deployment issue
-Selenium Test
-backend for the addInvoice
-Front end for the addInvoice
-Added both Admin/Trainer CreateInvoice form to be able to create the invoice
-Added …
=> feat(FWS-78):Ability To Create An Invoice

docker-compose.dev.yml, fitwsarah_frontend/src/views/HomePage/Home.js, src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfig.java
=> Fixing access token problem

src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java
Jira Ticket:
https://champlainsaintlambert.atlassian.net/browse/FWS-55
https://champlainsaintlambert.atlassian.net/browse/FWS-78
https://champlainsaintlambert.atlassian.net/browse/FWS-86
What is this PR about:
This PR is about fixing the controller integrated test for all three of my stories this sprint due to deployment issues when i was developing features all my tests would work and would cover my code in jacoco. The integrated test for the HandleAppointmentRequest(), getAllInvoices and the addInvoice().
WHat was changed:
-The two controller integrated files were missing the @SpringBootTest 
-Added a way to test the LocalDateTime part of the addInvocie Test.
=> bug(FWS): Controller Integrated Tests fixed for all three of my stories

fitwsarah_frontend/src/components/clientProfile/setting.js, fitwsarah_frontend/src/components/feedback/newFeedbackBtn.js, fitwsarah_frontend/src/views/ContactMePage/ContactMeView.js
fixed endpoint bug, the system does not recognize setProfile as a state update if its not with the profile constant, will result in a blank page.
=> fixed endpoint bug + profile

fitwsarah_frontend/public/LanguageContext/en/adminCoachNotes.json, fitwsarah_frontend/public/LanguageContext/en/trainerCoachNotes.json, fitwsarah_frontend/public/LanguageContext/fr/adminCoachNotes.json, fitwsarah_frontend/public/LanguageContext/fr/trainerCoachNotes.json, fitwsarah_frontend/src/App.js, fitwsarah_frontend/src/LanguageConfig/i18n.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminCoachNotes.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminCoachNotes.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminPanel.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCoachNotes.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCoachNotes.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerPanel.js, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteService.java, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteController.java, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteServiceImplTest.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-94
This ticket concerns being able to view all the coach notes in the system from the admin/trainer panel. This ticket is important because as an admin/trainer I want to be able to see all the coach notes in the system.
-3 types of testing
-Selenium Test
-backend for the getAllCoachNotes
-Front end for the getAllCoachNotes
-Added both Admin/Trainer panel invoice box and their own Coach Notes page
**UI Change:**
After Trainer Panel:
After clicking Coach Notes:
=> feat(Fws-94): Ability To View All Coach Notes

fitwsarah_frontend/public/LanguageContext/en/adminCoachNotes.json, fitwsarah_frontend/public/LanguageContext/en/trainerCoachNotes.json, fitwsarah_frontend/public/LanguageContext/fr/adminCoachNotes.json, fitwsarah_frontend/public/LanguageContext/fr/trainerCoachNotes.json, fitwsarah_frontend/src/views/AdminPanelPage/AdminCoachNotes.css, fitwsarah_frontend/src/views/AdminPanelPage/AdminCoachNotes.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminCreateCoachNotes.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCoachNotes.css, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerCoachNotes.js, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteService.java, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/datalayer/CoachNoteRepository.java, src/main/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteController.java, src/main/resources/schema-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/businesslayer/CoachNoteServiceImplTest.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/datalayer/CoachNoteRepositoryTest.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/coachnotesubdomain/presentationlayer/CoachNoteControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-95
This ticket is about being able to update a coach note in the personal trainer/admin panel so that the personal trainer can change information that isn't to their liking like the content_EN and the content_FR of the coach note. The reason why this is important is because like I said before the personal trainer/admins need to be able to update the information of every coach note if they feel like it if the coach note isn't to their liking.
-Selenium Test
-backend for the updateCoachNoteById
-Front end for the updateCoachNoteById
-Edit …
=> feat(Fws-95): Ability To Update A Coach Note

fitwsarah_frontend/public/LanguageContext/en/adminPanel.json, fitwsarah_frontend/public/LanguageContext/en/filter.json, fitwsarah_frontend/public/LanguageContext/fr/adminPanel.json, fitwsarah_frontend/public/LanguageContext/fr/filter.json, fitwsarah_frontend/src/components/AdminPanel/Filter.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceRepository.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceController.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceUniyTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-40
Context:
This ticket is about the filter functionality for the invoices table.
Changes
Added search filter feature in invoices
Added filter button in TrainerInvoices and Admin
Affects Personal Trainer and Admin
-Added 4 kinds of testing
- Added localization
UI:
Changes
=> Feat(FWS-40): Ability to Filter Invoices by Fields

fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.js, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceService.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceRepository.java, src/main/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceController.java, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/businesslayer/InvoiceServiceUniyTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/datalayer/InvoiceRepositoryTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/accountsubdomain/presentationlayer/InvoiceControllerUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/availabilitiessubdomain/businesslayer/AvailabilityServiceUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-92
Context:
This ticket is about deleting an invoice as an admin/personal trainer.
Changes
Admin and Personal trainer can now delete invoices for a specific member
Added 4 types of testing: Repository, Service Unit and Controller testing
-Added Selenium testing
UI Changes
=> Feat(FWS-92):Ability To Delete Invoices

fitwsarah_frontend/package-lock.json, fitwsarah_frontend/package.json, fitwsarah_frontend/public/LanguageContext/en/appointment.json, fitwsarah_frontend/public/LanguageContext/fr/appointment.json, fitwsarah_frontend/src/components/clientProfile/Appointment.css, fitwsarah_frontend/src/components/clientProfile/Appointment.js, fitwsarah_frontend/src/views/ProfilePage/Account.js, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentService.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceImpl.java, src/main/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentController.java, src/main/resources/data-mysql.sql, src/test/java/EndToEndTesting.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/businesslayer/AppointmentServiceUnitTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java, src/test/java/com/fitwsarah/fitwsarah/appointmentsubdomain/presentationlayer/AppointmentControllerUnitTest.java
https://champlainsaintlambert.atlassian.net/browse/FWS-90
Context:
This ticket is about user being able to cancel and reschedule appointments
Changes
- Added cancel button for requested appointments
- Added cancel button for scheduled appointments
- Added reschedule button for schedule appointments
- Added reschedule and canceling functions
UI Changes
=> feat(FWS-90): Ability to cancel or reschedule appointment

fitwsarah_frontend/public/LanguageContext/en/adminInvoices.json, fitwsarah_frontend/public/LanguageContext/en/trainerInvoices.json, fitwsarah_frontend/public/LanguageContext/fr/adminInvoices.json, fitwsarah_frontend/public/LanguageContext/fr/trainerInvoices.json, fitwsarah_frontend/src/views/AdminPanelPage/AdminAnalytics.js, fitwsarah_frontend/src/views/AdminPanelPage/AdminInvoices.js, fitwsarah_frontend/src/views/PersonalTrainerPanel/TrainerInvoices.js
https://champlainsaintlambert.atlassian.net/browse/FWS-96
This ticket is about adding localization for the trainer/admin panel invoice tab.
-Localization for trainerInvoice and adminInvoice
**UI Change:**
English Trainer Invoices:
French Trainer Invoices:
=> bug(FWS-96): Fix-Localization-For-Invoices

src/main/java/com/fitwsarah/fitwsarah/authenticationsubdomain/presentationlayer/SecurityConfig.java
=> Fix problem
